Add new option: DiscoveryIgnoreReplicaHostnameFilters
openark/orchestrator pull request #102
Opened 2017-03-16 08:13 UTC by sjmudd

This is used to allow us to avoid false positive discoveries of servers which look like replicas but which are not. It also allows us to not try to discover servers which we may not be able to reach
due to firewall holes even though we can see them referenced by a master.

- [x] contributed code is using same conventions as original code
- [x] code is formatted via `gofmt` (please avoid `goimports`)
- [x] code is built via `./build.sh`
- [x] code is tested via `go test ./go/...`

2017-03-16 08:28 UTC, shlomi-noach requested changes

2017-03-16 08:28 UTC, shlomi-noach commented on go/inst/instance_dao.go
> +
please move this function somewhere more generic, such as `go/inst/instance_utils.go`

2017-03-16 08:28 UTC, shlomi-noach commented on go/inst/instance_dao.go
> +		result = append(result, instance)
:+1:

2017-03-16 08:28 UTC, shlomi-noach commented on go/logic/orchestrator.go
> +
:+1:

2017-03-16 09:28 UTC, sjmudd commented on go/inst/instance_dao.go
> +
ok. will change.

2017-03-16 09:34 UTC, sjmudd commented
I relocated the function as requested.

2017-03-16 09:53 UTC, shlomi-noach requested changes

2017-03-16 09:53 UTC, shlomi-noach commented on go/inst/instance_dao2_test.go
> +}
Sorry, this should move to be in `instance_utils_test.go`, following the move of `RegexpMatchPatterns` to `instance_utils.go`

2017-03-16 22:47 UTC, sjmudd commented
Thanks for your patience, and hopefully this works for you.
Also fixed a comment typo to keep golint happy.

2017-03-19 06:07 UTC, shlomi-noach commented on go/logic/orchestrator.go
> +		replicaKey := replicaKey // not needed? no concurrency here?
correct, no concurrency here; keep it anyhow...

2017-03-19 06:07 UTC, shlomi-noach approved these changes

2017-03-19 06:08 UTC, merged