Add IO thread lag to Instance struct
openark/orchestrator pull request #1020
Opened 2019-11-14 22:45 UTC by kbanman

Related issue: https://github.com/github/orchestrator/issues/1019

### Description

This PR adds a `IOThreadLagSeconds` property to the Instance struct, allowing for awareness of network and disk latency slowing binlogs from being read by replica nodes.

- [ ] contributed code is using same conventions as original code
- [ ] code is formatted via `gofmt` (please avoid `goimports`)
- [ ] code is built via `./build.sh`
- [ ] code is tested via `go test ./go/...`

2019-11-17 06:43 UTC, shlomi-noach requested changes
Thanks you! As per discussion on https://github.com/github/orchestrator/issues/1019, I think Pseudo-GTID does not have a good-enough interval to measure replication lag; a `pt-heartbeat` or similar mechanism would be better. Please also see comments inline. I'm sorry!

2019-11-17 06:43 UTC, shlomi-noach commented on go/inst/instance_dao.go
> +			_, pseudoGtidText, err := FindLastPseudoGTIDEntry(instance, instance.RelaylogCoordinates, nil, false, &instance.Binlog_format)
This is a relatively resource heavy operation. It's fine to run when you're in need to relocate a replica, but I wouldn't want to run this every 5 seconds as part of probing a server.

2019-11-17 06:43 UTC, shlomi-noach commented on go/inst/instance_topology_dao.go
> +	queryExp, err := regexp.Compile(`drop view if exists (.+)._asc:(.+)`)
This regex is only true assuming you use `AutoPseudoGTID`

2019-11-17 06:43 UTC, shlomi-noach commented on go/inst/instance_topology_test.go
> +	entryTime, err := extractPseudoGTIDTime(gtidText)
Thank you for adding a test!

2019-11-26 01:00 UTC, kbanman commented
Thanks for the feedback @shlomi-noach. 

Would you be open to adding the functionality of `pt-heartbeat` to orchestrator? Seems it would be a good fit for an opt-in feature.

2019-11-26 08:05 UTC, shlomi-noach commented
> Would you be open to adding the functionality of pt-heartbeat to orchestrator? Seems it would be a good fit for an opt-in feature.

I'm ambivalent. It's certainly within `orchestrator`'s capabilities: `orcehstrator` knows which is the `master` host, can validate it's writable, etc.

But that would mean `orchetrator` turns into a critical path in the topology's replication health. If `orchestrator` went down - the cluster would _seem to be lagging_ (even if not really lagging). Not sure I like this dependency on `orchestrator`.

2019-12-04 23:43 UTC, closed without merging