Add CountDistinctOkInstanceKeys to discovery aggregate metrics.
openark/orchestrator pull request #111
Opened 2017-03-23 21:21 UTC by sjmudd

We had a count of the different number of hosts seen in the period,
and the different number of failures but given that in the monitoring
period successful and failed discoveries may happen for the same
host we can't infer the missing metric. This patch adjusts that by
providing the 3 values:

* CountDistinctInstanceKeys
* CountDistinctOkInstanceKeys (new)
* CountDistinctFailedInstanceKeys

## A Pull Request should be associated with an Issue.

> We wish to have discussions in Issues. A single issue may be targeted by multiple PRs.
> If you're offering a new feature or fixing anything, we'd like to know beforehand in Issues,
> and potentially we'll be able to point development in a particular direction.

Related issue: https://github.com/github/orchestrator/issues/0123456789

> Thank you! We are open to PRs, but please understand if for technical reasons we are unable to accept each and any PR

### Description

This PR [briefly explain what is does]

> In case this PR introduced Go code changes:

- [ ] contributed code is using same conventions as original code
- [ ] code is formatted via `gofmt` (please avoid `goimports`)
- [ ] code is built via `./build.sh`
- [ ] code is tested via `go test ./go/...`

2017-03-24 05:24 UTC, shlomi-noach approved these changes

2017-03-28 09:50 UTC, shlomi-noach requested changes

2017-03-28 09:50 UTC, shlomi-noach commented on go/discovery/aggregated.go
> +			x := names["OkInstanceKeys"]
Can you please make all these strings a type? See for example [AnalysisCode](https://github.com/github/orchestrator/blob/0333dfa6c37bd5c14fd4e9f13cb0a841d1299745/go/inst/analysis.go#L23-L54)

2017-04-02 07:44 UTC, sjmudd commented
You asked for the strings to be made to types and I've done that now.

2017-04-05 10:39 UTC, shlomi-noach approved these changes

2017-04-05 10:39 UTC, merged