add replication delay command
openark/orchestrator pull request #1267
Opened 2020-11-16 19:35 UTC by marcosvm

Related issue: https://github.com/openark/orchestrator/issues/1266

### Description

This PR adds a command to delay replication on a specific instance keeping the current replication threads status.

Please make sure that:

- [ ] contributed code is using same conventions as original code

Please make sure the PR passes CI tests. For your information, CI tests the following:

- [ ] - code is formatted via `gofmt` (please avoid `goimports`)
- [ ] - code passes compilation
- [ ] - code passes unit tests
- [ ] - code passes integration tests with MySQL backend
- [ ] - code passes integration tests with SQLite backend
- [ ] - There are no orphaned docs/ pages (there's some link in the docs to point to any page)
- [ ] - upgrade from previous version (`master` branch) is successful

2020-11-17 08:04 UTC, shlomi-noach requested changes
Thank you! This looks good, with a few requests for changes. Please consider adding a `delay-replication` command in https://github.com/openark/orchestrator/blob/master/resources/bin/orchestrator-client

2020-11-17 08:04 UTC, shlomi-noach commented on go/inst/instance_topology_dao.go
> +func DelayReplication(instanceKey *InstanceKey, seconds int) error {
Let's have this function validate `seconds` value is `>= 0`. I see it's been validated in the API, but it's important that the function self-validates its own input. If you like, you can then remove the ` seconds < 0 ` validation from https://github.com/openark/orchestrator/pull/1267/files#diff-535924bad43b8347b4337b267fbbef99095e909ac11bf5d458462a28d1afbf52R1592

2020-11-17 08:04 UTC, shlomi-noach commented on go/http/api.go
> +	Respond(r, &APIResponse{Code: OK, Message: fmt.Sprintf("Replication delayed: %+v", instanceKey), Details: nil})
May as well throw `seconds` into the output:
```suggestion
	Respond(r, &APIResponse{Code: OK, Message: fmt.Sprintf("Replication delayed: %+v", instanceKey), Details: seconds})
```

2020-11-17 08:04 UTC, shlomi-noach commented on go/inst/instance_topology_dao.go
> +			log.Infof("%s on %+v as part of DelayReplication", cmd, *instanceKey)
```suggestion
			log.Infof("DelayReplication: %s on %+v", cmd, *instanceKey)
```

2020-11-17 08:04 UTC, shlomi-noach commented on go/inst/instance_topology_dao.go
> +	return nil
```suggestion
	AuditOperation("delay-replication", instanceKey, fmt.Sprintf("set to %d", seconds))
	return nil
```

2020-11-18 03:52 UTC, marcosvm commented
@shlomi-noach I added the modifications you suggested. Thank you for the review.

2020-11-19 12:23 UTC, shlomi-noach approved these changes

2020-11-19 12:23 UTC, merged