Add missing use case for GetNextBinlogCoordinatesToMatch when moving …
openark/orchestrator pull request #19
Opened 2016-12-16 15:42 UTC by sjmudd

## A Pull Request should be associated with an Issue.

See https://github.com/outbrain/orchestrator/pull/286.

The commit text incorrectly mentions only the last commit but the patch includes the full changes necessary to move a 5.7 replica around directly or indirectly under a 5.6 master when pseudo-GTID is in use and the 5.7 replica is replicating from a 5.7 intermediate master.

### Description

Issue caused by the 5.7 intermediate master generating ANONYMOUS GTID events which confuse the existing matching process.

2016-12-27 21:31 UTC, sjmudd commented
Let me try and explain the 2 use cases that this PR is trying to fix:

(a) moving a 5.7 slave (without binlogs) which is under a 5.7 intermediate master which itself is under a 5.6 master under that master or any other 5.6 master in the same topology.

Here the 5.6 binlog stream is "normal", but the binlog stream received by the 5.7 slave (and stored in the relay logs) has additional ANONYMOUS gtid events in them.  These events need to be filtered out on the 5.7 slave's relay logs.

(b) moving a 5.7 slave (which is under a 5.6 master or intermediate master) under a 5.7 intermediate master which has binlogs.

In this case the 5.7 slave has no "anonymous GTID events" as it replicates from the 5.6 master but the 5.7 intermediate master does have these events and they must be ignored in order to compare events.

In both cases "hiding" the events, as I had done previously does not work as using the binlog filter means that in the situation where replication is stoppped on the IM or the slave the position at which the stop happens _may_ be on an anonymous GTID event. If that's the case the event will be skipped and the current logic will not think that it's matched things correctly thus giving an error.

I hope that this longer description makes sense.

2017-01-11 09:10 UTC, sjmudd commented
Can I do anything more to help pull in this change?

2017-02-09 06:30 UTC, shlomi-noach commented
I'm picking up on this. Meanwhile I'm going to make a release without this.

2017-02-12 12:31 UTC, shlomi-noach requested changes

2017-02-12 12:31 UTC, shlomi-noach commented on go/inst/instance_binlog_dao.go
> +func rpad(coordinates BinlogCoordinates, length *int) string {
Can you please move this function to `binlog.go` as opposed to `binlog_dao.go`?

2017-02-12 12:31 UTC, shlomi-noach commented on go/inst/instance_binlog_dao.go
> +		other.FlavorNameAndMajorVersion() != "MySQL-5.7" { // new master is NOT  5.7
I'm curious, why `MySQL-5.6` and `MySQL-5.7` as opposed to `5.6` and `5.7`? Does the problem not happen with Percona `5.6` & `5.7`?

2017-02-12 12:31 UTC, shlomi-noach commented on go/inst/instance_binlog_dao.go
> +			instanceEvent = *event // make a physical copy
curious. Why a physical copy?

2017-02-16 22:16 UTC, sjmudd commented on go/inst/instance_binlog_dao.go
> +		other.FlavorNameAndMajorVersion() != "MySQL-5.7" { // new master is NOT  5.7
I do not use Percona so can not add comments for something I'm not sure about.  (I guess it should work though.) Also when I added this code there was no specific percona flavours to check for so the question was not relevant at the time.

2017-02-16 22:30 UTC, sjmudd commented on go/inst/instance_binlog_dao.go
> +func rpad(coordinates BinlogCoordinates, length *int) string {
That should be done now. Still having a bit of trouble figuring out the workflow here. thanks for your patience.

2017-02-16 22:32 UTC, sjmudd commented on go/inst/instance_binlog_dao.go
> +			instanceEvent = *event // make a physical copy
You're comparing two events. If you write to one of them and have 2 pointers pointing to the same event both will be the same and that's not what is wanted. Hence taking a physical copy ensures that you compare 2 different events. That was my intention anyway.

2017-02-19 06:53 UTC, shlomi-noach approved these changes

2017-02-19 06:54 UTC, merged

2017-02-19 06:54 UTC, shlomi-noach commented
thank you!