Show the count and not the list of server if the number being polled …
openark/orchestrator pull request #22
Opened 2016-12-28 20:01 UTC by sjmudd

…is over MaxOutdatedKeysToShow (default: 10)

### Issue

This change is to prevent the logging of all the outdated keys (better term would be _polled hosts_ or _polled instances_) when the number grows over a certain threshold. When a large number of servers are being polled this list just gets to big and intrusive.

I have been using a variation of this code on my own patched code for some time. It was not configurable in my case. This allows for the current behaviour by default for small environments, and changes to use my preferred output if the number of monitored servers goes over the configured limit.

### Description

Add a new config setting: MaxOutdatedKeysToShow, default 10, which if exceeded will adjust the logging to just show: `polling NNN outdated keys` rather than `outdated keys: [ host1:12345, host2:12345, ... hostn:12345 ]`

2016-12-28 20:53 UTC, sjmudd commented
Note: if you prefer a boolean setting to just show the count rather than the instance list I can change this patch to do that.

2016-12-29 09:47 UTC, shlomi-noach requested changes

2016-12-29 09:47 UTC, shlomi-noach commented on go/config/config.go
> +		MaxOutdatedKeysToShow:                        10,
Please make the default larger (say `64`), and set your own personal config to `10`

2016-12-29 11:08 UTC, sjmudd commented on go/config/config.go
> +		MaxOutdatedKeysToShow:                        10,
ok. will change value as suggested.

2016-12-29 11:13 UTC, shlomi-noach approved these changes

2016-12-29 11:13 UTC, merged