Allow for optional post-processing after starting orchestrator
openark/orchestrator pull request #230
Opened 2017-07-06 10:44 UTC by sjmudd

This is a corrected version of https://github.com/github/orchestrator/pull/228. The commit message referenced a different project.

This is because of https://github.com/github/orchestrator/issues/227

A solution would be to add the following to /etc/orchestrator_profile

--- snip ---
post_start_daemon_hook () {
	sleep 1
}
--- snip ---

No go code changes, just the init script.

2017-07-10 05:44 UTC, shlomi-noach requested changes
make sure to hide `post_start_daemon_hook`'s output, if there is one.

2017-07-10 05:44 UTC, shlomi-noach commented on etc/init.d/orchestrator.bash
> +	post_start_daemon_hook
you must make sure that `post_start_daemon_hook` doesn't generate output, since you catch the output later on -- it's the PID

2017-07-10 06:06 UTC, sjmudd commented on etc/init.d/orchestrator.bash
> +	post_start_daemon_hook
Is it not sufficient to add a comment into the existing function?
If not I can make another function call post_start_daemon_hook and redirect output there. It's a bit more convoluted but can be done if you want that.

2017-07-10 06:08 UTC, sjmudd commented on etc/init.d/orchestrator.bash
> +	post_start_daemon_hook
In my case the fix may work outside of the start_daemon function in which case the problem does not arrive. I'll check and make an approprpriate change.

2017-07-10 06:11 UTC, shlomi-noach commented on etc/init.d/orchestrator.bash
> +	post_start_daemon_hook
I beliebe you can `(post_start_daemon_hook 1>&2)`. That thould do the trick.

2017-07-10 06:18 UTC, sjmudd commented on etc/init.d/orchestrator.bash
> +	post_start_daemon_hook
Well go with that then.

2017-07-10 22:22 UTC, sjmudd commented
So made change as requested redirecting stdout to stderr.

2017-07-11 05:03 UTC, shlomi-noach approved these changes

2017-07-11 05:03 UTC, merged