Fix detection of Go 1.10.x
openark/orchestrator pull request #486
Opened 2018-05-06 19:27 UTC by dveeden

Fedora 28 ships with go 1.10.x which build.sh detects as too old, while it isn't too old.
This PR fixes that by a more restrictive regex.

```
$ go version
go version go1.10.1 linux/amd64
```

2018-05-06 19:50 UTC, dveeden commented
Looks like this is a duplicate of #458

2018-05-07 04:27 UTC, shlomi-noach requested changes
We would need a better method, because the version could be `1.8` or `1.9` (no trailing `.`).

I have something else in mind, let me push a change.

2018-05-07 04:33 UTC, shlomi-noach approved these changes

2018-05-07 04:33 UTC, shlomi-noach commented
I pushed a change to your PR, and it should be good now: explicitly allowing `go1.8`, `go1.9`, `go1.10`, and anything else is disallowed.

2018-05-09 11:37 UTC, merged