Stop graceful master takeover immediately when attempting to promote an ignored host
openark/orchestrator pull request #570
Opened 2018-07-31 15:45 UTC by dougfales

Related issue: https://github.com/github/orchestrator/issues/569

### Description

During a graceful master takeover, this simply checks the `IsBannedFromBeingCandidateReplica` function for the newly designated master before doing anything else. By checking this early and failing early, we avoid making any changes to the topology for a promotion we know will fail at the outset. 

- [ ] contributed code is using same conventions as original code
- [ ] code is formatted via `gofmt` (please avoid `goimports`)
- [ ] code is built via `./build.sh`
- [ ] code is tested via `go test ./go/...`

(Thanks @zmoazeni for the idea!)

2018-08-05 05:59 UTC, shlomi-noach requested changes
Thank you, looking good! The same check should also apply for this case: https://github.com/dougfales/orchestrator/blob/4b1833b73f8c6c110464a07fb585a875707d8e85/go/logic/topology_recovery.go#L1670

i.e. the check should be made whetehr the designated instance is explicitly indicated (the case you handle) or implied (master has a single direct replica, hence that's the designated instance).

2018-08-07 21:34 UTC, dougfales commented
Great point! I pulled the check outside of the conditional so that it will be done with the `designatedInstance`, regardless of whether that instance was indicated by the user or selected by orchestrator. 

I set up a local test env with three replicas, banning one of them via `PromotionIgnoreHostnameFilters`, and I verified that the error is reported immediately in both cases:
1. When I pass the banned replica explicitly.
2. When I make the banned replica the only descendant of the current master and therefore orchestrator tries to choose it as the `designatedInstance`.

Please let me know if there's anything else I should add or clean up here. Thanks!

2018-08-12 05:07 UTC, shlomi-noach approved these changes

2018-08-12 05:10 UTC, merged

2018-08-13 13:10 UTC, dougfales commented
Thanks Shlomi!