orchestrator-client: Add credentials to environment variables
openark/orchestrator pull request #675
Opened 2018-10-30 15:32 UTC by mateusduboli

Related to issue #674

2018-10-30 16:23 UTC, shlomi-noach requested changes
Thank you for this. The PR makes sense.
Can you please rename the variables to something more descriptive, such as `ORCHESTRATOR_AUTH_USER`, `ORCHESTRATOR_AUTH_PASSWORD`?

2018-10-31 15:55 UTC, shlomi-noach approved these changes

2018-11-01 06:55 UTC, merged

2018-11-20 11:28 UTC, sjmudd commented
This actually breaks having credentials in the `ORCHESTRATOR_API` variable, e.g. of the form: 

```
export ORCHESTRATOR_API=https://some_user:some_password@orchestrator.example.com
```

The fix for this seems to me to be to only set `basic_auth` if `ORCHESTRATOR_AUTH_USER` is not empty, as otherwise the value is populated with `:` which is useless.

2018-11-20 11:33 UTC, sjmudd commented
Also the usage of `--basic --user "${basic_auth}"` if `${basic_auth}` is not set will break. This is not taken into account.

I will offer an updated PR for this which should address both issues.