Add more detailed timing metrics to orchestrator
openark/orchestrator pull request #79
Opened 2017-02-15 07:54 UTC by sjmudd

This rather large patch brings in code from booking.com which does the following:

Signal handling:
* handle SIGTERM

discoverInstance():
* Add timing metrics: talking to instance, backend timings and total
  time for each discovery using vendor/github.com/sjmudd/stopwatch
  for managing timing counters.

Add new api calls:
* /api/discovery-metrics-raw/:seconds
* /api/discovery-metrics-aggregated/:seconds
* /api/backend-query-metrics-raw/:seconds
* /api/backend-query-metrics-aggregated/:seconds

New configuration setting:
* DiscoveryCollectionRetentionSeconds which determines the amount of time
  individual discovery statistics are kept for.

checkMaxScale:
* move maxscale checks out of inst.ReadTopologyInstanceBufferable()

Basically the change adds more detailed metrics which can be seen in logging but also makes these metrics retrievable by API calls to orchestrator. Both raw and aggregated forms are provided to give the user to choose what works best.

These changes were added to our code to help us identify performance problems on our large setup and have been running for some time.

- [x] contributed code is using same conventions as original code
- [x] code is formatted via `gofmt` (please avoid `goimports`)
- [x] code is built via `./build.sh`
- [x] code is tested via `go test ./go/...`

2017-02-15 15:22 UTC, shlomi-noach requested changes
See questions within review.

I used a lot of :+1: for self-marking pieces of code I've reviewed.

I wish to be able to turn this feature off. Id expect to see a `if DiscoveryCollectionRetentionSeconds > 0 { // do it }`, but it seems to me like this is always on.

2017-02-15 15:22 UTC, shlomi-noach commented on go/logic/orchestrator.go
> +				os.Exit(0)
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/logic/orchestrator.go
> +	signal.Notify(c, syscall.SIGTERM)
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/config/config.go
> +	DiscoveryCollectionRetentionSeconds          uint     // Number of seconds to retain the discovery collection information
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/config/config.go
> +		DiscoveryCollectionRetentionSeconds:          120,
Does this mean `DiscoveryCollectionRetentionSeconds` is ON by default? What is the change in behavior I can expect on my own setup as I deploy this?

2017-02-15 15:22 UTC, shlomi-noach commented on docs/using-the-web-api.md
> +* `/api/backend-query-metrics-aggregated/:seconds`: return a set of aggregated values based on the raw numbers above
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/app/http.go
> +	standardHttp(continuousDiscovery)
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/app/http.go
> +func Http(continuousDiscovery bool) {
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/app/http.go
> +
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/http/api.go
> +	log.Debugf("DiscoveryQueueMetricsRaw data: %+v", metrics)
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/http/api.go
> +		r.JSON(200, &APIResponse{Code: ERROR, Message: "Unable to generate discovery queue aggregated metrics"})
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/http/api.go
> +	this.registerRequest(m, "discovery-metrics-aggregated/:seconds", this.DiscoveryMetricsAggregated)
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/http/api.go
> +	this.registerRequest(m, "backend-query-metrics-aggregated/:seconds", this.BackendQueryMetricsAggregated)
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/logic/orchestrator.go
> +	instance, err = inst.ReadTopologyInstanceBufferable(&instanceKey, config.Config.BufferInstanceWrites, latency)
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/logic/orchestrator.go
> +			err)
Is it possible that between the `discoveryMetrics.Append(...)` call and this line, the returned value of `ElapsedSeconds(...)` are incompatible? Would this be confusing?

2017-02-15 15:22 UTC, shlomi-noach commented on go/logic/orchestrator.go
> +		latency.ElapsedSeconds("instance"))
👍

2017-02-15 15:22 UTC, shlomi-noach commented on vendor/github.com/sjmudd/stopwatch/named_stopwatch.go
> +}
I see no synchronization code here. What happens on concurrent writes? Is it possible to call `Keys()` or `Reset()` while calling `AddMany()` or `Delete()`?

2017-02-15 15:22 UTC, shlomi-noach commented on go/collection/collection.go
> +}
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/collection/collection_test.go
> +}
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/discovery/aggregated.go
> +}
:+1:

2017-02-15 15:22 UTC, shlomi-noach commented on go/discovery/metric.go
> +func MetricsEqual(m1, m2 [](*Metric)) bool {
You can use https://golang.org/pkg/reflect/#DeepEqual

2017-02-19 08:56 UTC, shlomi-noach requested changes

2017-02-19 08:56 UTC, shlomi-noach commented on go/discovery/metric_json.go
> +type myfloat float64
Please rename to `formattedFloat` or something

2017-02-19 08:56 UTC, shlomi-noach commented on go/discovery/metric_json.go
> +}
:+1:

2017-02-19 08:56 UTC, shlomi-noach commented on go/http/api.go
> +}
:+1:

2017-02-19 08:56 UTC, shlomi-noach commented on go/http/api.go
> +
:+1:

2017-02-19 08:56 UTC, shlomi-noach commented on go/inst/instance_dao.go
> +	}()
:+1:

2017-02-19 08:56 UTC, shlomi-noach commented on go/inst/instance_dao.go
> +	return nil, fmt.Errorf("ReadTopologyInstanceBufferable failed: %v", err)
:+1:

2017-02-19 08:56 UTC, shlomi-noach commented on go/inst/instance_dao.go
> +				ifnull(nullif(promotion_rule, ''), 'neutral') as promotion_rule
:+1:

2017-02-19 08:56 UTC, shlomi-noach commented on go/logic/orchestrator.go
> +	latency.Start("total") // start the total stopwatch (not changed anywhere else)
:+1:

2017-02-19 09:23 UTC, shlomi-noach requested changes
You misunderstood my comment about `DeepEqual`

2017-02-19 09:23 UTC, shlomi-noach commented on go/discovery/metric.go
>  func MetricsEqual(m1, m2 [](*Metric)) bool {
`return reflect.DeepEqual(m1,m2)`

2017-02-19 09:23 UTC, shlomi-noach commented on go/discovery/metric.go
> +		if !reflect.DeepEqual(m1[i],m2[i]) {
You want to use `DeepEqual` on everything, not on a per-element basis.

2017-02-19 09:25 UTC, shlomi-noach commented
https://github.com/github/orchestrator/pull/79#discussion_r101912521

2017-02-19 09:26 UTC, shlomi-noach commented on go/logic/orchestrator.go
> +			instanceLatency,
:+1:

2017-02-21 16:36 UTC, shlomi-noach commented
@sjmudd the last outstanding issue is about DeepEquals, see https://github.com/github/orchestrator/pull/79#discussion_r101912521

2017-02-23 13:09 UTC, sjmudd commented on go/discovery/metric_json.go
> +type myfloat float64
done.

2017-02-23 13:10 UTC, sjmudd commented
I think all your concerns are now addressed. Not sure how to grab a quick view of anything that's pending. If I've missed something please let me know. Thanks.

2017-02-23 13:57 UTC, shlomi-noach approved these changes

2017-02-23 18:44 UTC, merged

2017-02-24 06:33 UTC, sjmudd commented
+1 Thanks for taking this.