Make executeCheckAndRecoverFunction show unhandled analysis entries.
openark/orchestrator pull request #81
Opened 2017-02-16 17:37 UTC by sjmudd

Current code does not make this very visible and the code path should not get here anyway. However, if it does it indicates that the analysis phase is not completely correct or we are not handling the situation correctly. Both situations probably need to be identified and resolved.

- [x] contributed code is using same conventions as original code
- [x] code is formatted via `gofmt` (please avoid `goimports`)
- [x] code is built via `./build.sh`
- [x] code is tested via `go test ./go/...`

2017-02-19 07:04 UTC, shlomi-noach requested changes

2017-02-19 07:04 UTC, shlomi-noach commented on go/logic/topology_recovery.go
> +
Incorrect change of logic. Consider the behavior of `case inst.UnreachableMaster:`: it doesn't assign a `checkAndRecoverFunction` but instead issues an immediate `go emergentlyReadTopologyInstanceReplicas(...)`.

It should then `return false, nil, nil`. But in your code change it _does not_ return, but instead proceeds to execute the recovery function. Such function does not exist and proceeding is wrong.

2017-02-22 19:35 UTC, sjmudd commented on go/logic/topology_recovery.go
> +
Ok. Will handle this properly shortly. Thanks for the heads up.

2017-02-23 11:19 UTC, sjmudd commented
Hi Shlomi. thanks for brining up the problem with the change I proposed. it does look as if I'd missed the meaning of what was going on here. Bottom line, the original code has a reference to unhandled exceptions and I wanted to see if there were any and why.  I can change the code therefore to do the check properly by using the 

```
if checkAndRecoverFunction == nil
```

and adding a check to log if `if analysisEntry.Analysis != inst.NoProblem`.

Having said that I hadn't realised but in the same function `executeCheckAndRecoverFunction` you call in some cases `go emergentlyXXXX` which seems to be designed to trigger an instant discovery of one or more servers, but currently that's handled outside of the concurrency queueing mechanism.  For discovering a single server this may not be an issue but `emergentlyReadTopologyInstanceReplicas` bypasses the discovery queue which is intended to limit the number of concurrent concurrency attempts.  For a large replication chain you may trigger an extra X number of discoveries which might not be good, and might perhaps trigger later rights to the orchestrator backend to hit `max_connections`.

If you agree that analysis is correct then I'd like to modify these functions to "queue" their discoveries, but rather than doing this "at the end of the queue" to push the discovery request to the beginning.

This change in behaviour would seem to be fine, unless `executeCheckAndRecoverFunction` repeatedly triggers these `emergentlyXXX` functions, something which seems to be something I'm seeing as basically it bypasses the current FIFO discovery queue.

So maybe this is something to consider?

2017-02-23 12:47 UTC, sjmudd commented
I've pushed a further change to log only if the analysis is not `NoProblem` and is not "handled" which I think should resolve your concerns.

2017-02-24 07:28 UTC, sjmudd commented
The current patch, if you pull the latest changes in the branch, will only log that something has been missed if the problem is not NoProblem and if `if checkAndRecoverFunction == nil` is called. So no changes in behaviour: just some extra logging which hopefully will be useful. I can then follow up on that if I see (as I am) repeated occurrences of this being triggered.

So would you accept the PR as it is now so we can make progress?

Thanks for your thoughts on this.

2017-02-24 15:39 UTC, shlomi-noach approved these changes

2017-02-24 15:39 UTC, shlomi-noach commented on go/logic/topology_recovery.go
> +
:+1:

2017-02-24 15:40 UTC, merged